version: '3.8'

services:
  bot:
    build: .
    container_name: fashion_daemon_bot
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
