services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fashion_bot_main
    restart: always
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: python bot/main.py